@Test
public void testErrorRealm() throws Exception {
    Context context = new TesterContext();
    JNDIRealm realm = new JNDIRealm();
    realm.setContainer(context);
    realm.setUserSearch("");
    // Connect to something that will fail
    realm.setConnectionURL("ldap://127.0.0.1:12345");
    realm.start();
    count = 0;
    (new Thread(() -> {
        realm.authenticate("foo", "bar");
        count++;
    })).start();
    (new Thread(() -> {
        realm.authenticate("foo", "bar");
        count++;
    })).start();
    (new Thread(() -> {
        realm.authenticate("foo", "bar");
        count++;
    })).start();
    Thread.sleep(10);
    Assert.assertEquals(3, count);
}